# Site settings
title: Learning To Fly
email: rabi@kavoori.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.kavoori.com" # the base hostname & protocol for your site
twitter_username: rabi_rob
github_username:  kavoori
highlighter: pygments

permalink: /:year-:month-:day/:title.html

markdown: kramdown
kramdown:
  input: GFM
  fenced_code_blocks: true

paginate: 5